### PR TITLE
Support embed codes for private lessons

### PR DESCRIPTION
**Pull request by streeter**
Educreations now supports embedding private lessons. These include a lesson secret. This allows Versal to support that URL scheme now.

### CODE REVIEW

**Comment by streeter** [comment]
@possibilities and @dmcguinness, any chance of this getting merged?

**Comment by possibilities** [comment]
@streeter Chris, sorry you had to remind us about this!

We've found that some codes that worked before no longer work. E.g.:

```
<iframe width="480" height="300" src="https://www.educreations.com/lesson/embed/15383022/?ref=embed" frameborder="0" allowfullscreen></iframe>
```

**Comment by streeter** [comment]
Hm, let me look into it.

**Comment by streeter** [comment]
Got a fix in #19

**Comment by possibilities** [comment]
Thanks so much sir, I uploaded and approved it!

**Comment by possibilities** [comment]
We really appreciate the effort you put into it, e.g. including tests and everything!

**Pull request merged**
